-- Sprint 9 / ADR 0022 2026-05-31 addendum — driver self-onboarding schema.
--
-- PURELY ADDITIVE per Rule 4 + Rule 5:
--   * One new enum value on identity.IdTokenKind ('virtual_rfid')
--   * New table tenancy.org_email_domains + its policy enum
--   * New table agreements.driver_access_requests + its trigger + status enums
--   * Back-relation FK rows on Organization, DriverGroup, User, Installation
--     are implicit (Prisma-side only; no DB changes needed)
--
-- No DROP, no RENAME, no ALTER TYPE on existing enums or columns.
-- Existing rows survive unchanged — these are net-new tables and one
-- net-new enum value.
--
-- This file was hand-written (not generated by `prisma migrate dev`) because
-- the staging database has pre-existing drift on tenancy.OrganizationRole
-- that would have triggered a destructive reset. The drift is unrelated to
-- this migration and is left for separate operator action.
--
-- Apply with:  npx prisma migrate deploy
-- (Never `migrate dev` or `migrate reset` against staging — they would wipe
-- the 491 priced sessions + 5 active agreements + 6 clauses + 2 rate refs.)

-- ─── 1. IdTokenKind: add virtual_rfid ────────────────────────────────────────

ALTER TYPE "identity"."IdTokenKind" ADD VALUE IF NOT EXISTS 'virtual_rfid';

-- ─── 2. tenancy.OrgEmailDomainPolicy enum + table ────────────────────────────

CREATE TYPE "tenancy"."OrgEmailDomainPolicy" AS ENUM (
  'auto_join',
  'request_approval',
  'disabled'
);

CREATE TABLE "tenancy"."org_email_domains" (
  "id"                       UUID         NOT NULL DEFAULT gen_random_uuid(),
  "org_id"                   UUID         NOT NULL,
  "domain"                   TEXT         NOT NULL,
  "policy"                   "tenancy"."OrgEmailDomainPolicy"
                                         NOT NULL DEFAULT 'request_approval',
  "default_driver_group_id"  UUID,
  "created_at"               TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  "updated_at"               TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),

  CONSTRAINT "org_email_domains_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "org_email_domains_org_id_fkey"
    FOREIGN KEY ("org_id") REFERENCES "tenancy"."organizations" ("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "org_email_domains_default_driver_group_id_fkey"
    FOREIGN KEY ("default_driver_group_id") REFERENCES "agreements"."driver_groups" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "org_email_domains_domain_key"
  ON "tenancy"."org_email_domains" ("domain");

CREATE INDEX "org_email_domains_org_id_idx"
  ON "tenancy"."org_email_domains" ("org_id");

-- ─── 3. agreements.DriverAccessRequest enums + table ─────────────────────────

CREATE TYPE "agreements"."DriverAccessRequestTrigger" AS ENUM (
  'self_request',
  'email_domain_match'
);

CREATE TYPE "agreements"."DriverAccessRequestStatus" AS ENUM (
  'pending',
  'approved',
  'denied',
  'withdrawn'
);

CREATE TABLE "agreements"."driver_access_requests" (
  "id"                       UUID         NOT NULL DEFAULT gen_random_uuid(),
  "user_id"                  UUID         NOT NULL,
  "installation_id"          UUID         NOT NULL,
  "triggered_by"             "agreements"."DriverAccessRequestTrigger" NOT NULL,
  "org_email_domain_id"      UUID,
  "status"                   "agreements"."DriverAccessRequestStatus"
                                         NOT NULL DEFAULT 'pending',
  "reviewed_by_user_id"      UUID,
  "reviewed_at"              TIMESTAMPTZ(6),
  "denial_reason"            TEXT,
  "resulting_membership_id"  UUID,
  "created_at"               TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  "updated_at"               TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),

  CONSTRAINT "driver_access_requests_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "driver_access_requests_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "identity"."users" ("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "driver_access_requests_installation_id_fkey"
    FOREIGN KEY ("installation_id") REFERENCES "properties"."installations" ("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "driver_access_requests_org_email_domain_id_fkey"
    FOREIGN KEY ("org_email_domain_id") REFERENCES "tenancy"."org_email_domains" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "driver_access_requests_reviewed_by_user_id_fkey"
    FOREIGN KEY ("reviewed_by_user_id") REFERENCES "identity"."users" ("id")
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX "driver_access_requests_status_installation_id_idx"
  ON "agreements"."driver_access_requests" ("status", "installation_id");

CREATE INDEX "driver_access_requests_user_id_status_idx"
  ON "agreements"."driver_access_requests" ("user_id", "status");
