/**
 * driver-access-requests.ts — repository for the operator-inbox path
 * of driver self-onboarding (ADR 0022 / 2026-05-31 addendum,
 * Sprint 9 ENROLL-2).
 *
 * Five surfaces:
 *
 *   1. createSelfRequest — driver clicks "Request access to this
 *      charger" in the mobile app. We:
 *        a. Verify the installation exists.
 *        b. Reject if the driver already has an active DriverGroup
 *           membership covering this installation (no point logging
 *           a request for access they already have).
 *        c. Reject if the driver already has a pending request for
 *           the same installation (no spam).
 *        d. Write driver_access_requests with triggeredBy='self_request'.
 *        e. Send "access-request-submitted" email to the driver and
 *           "access-request-inbound" email to the org's main contact.
 *        f. Email failures fail OPEN (logged warn, response still 201)
 *           so a Resend outage / missing key never blocks the request.
 *
 *   2. listForOperator — paginated inbox view for an operator org.
 *      Scope-filtered to requests whose installation belongs to the
 *      requested orgId. Joined to user, installation, site, email
 *      domain, and reviewer rows for display. Totals tile included.
 *
 *   3. approveRequest — operator approves. We:
 *        a. Look up the request + the installation it targets.
 *        b. Pick the first DriverGroup attached to an active Agreement
 *           covering this installation (smallest member count to spread
 *           load; ties broken by createdAt asc — deterministic).
 *        c. Idempotency:
 *           - request.status already 'approved' AND the linked
 *             DriverGroupMembership still exists → return existing.
 *           - DriverGroupMembership already exists for (group, user)
 *             → silently mark approved + link existing.
 *        d. Otherwise create membership + flip request to approved in
 *           one transaction.
 *        e. Send "access-request-approved" email.
 *
 *   4. denyRequest — operator denies with a required reason. We:
 *        a. Reject re-deny of an already-denied/approved/withdrawn row
 *           (idempotency at the action level — the inbox UI hides these).
 *        b. Set status='denied', denialReason, reviewedBy, reviewedAt.
 *        c. Send "access-request-denied" email.
 *
 * Authority check (reviewer must have member.write on the installation's
 * org) lives at the route layer via assertPermission — the repo trusts
 * the caller's pre-check.
 */
import type { PrismaClient } from "../generated/prisma/client";
import type { Env } from "../bindings";
import { sendEmail } from "../lib/email";

/**
 * Typed escape hatch for the new agreements.driver_access_requests
 * model. The Prisma client in this worktree is regenerated by sibling
 * agents on their commits; until that lands across the merge, the
 * local generated client may not yet expose `db.driverAccessRequest`.
 * Casting to `any` for that accessor lets us write the data-layer code
 * today without coupling to the regeneration cadence.
 *
 * `driverGroup` and `driverGroupMembership` ARE present on the
 * generated client (Sprint 9 / ADR 0019), so they keep their types.
 *
 * Removed once ENROLL-1 + ENROLL-3 land and the merged generated
 * client carries the new accessor natively.
 */
type AccessRequestsDb = PrismaClient & {
  driverAccessRequest: any;
};

function darDb(db: PrismaClient): AccessRequestsDb {
  return db as unknown as AccessRequestsDb;
}
import { renderAccessRequestSubmittedEmail } from "../lib/email-templates/access-request-submitted";
import { renderAccessRequestApprovedEmail } from "../lib/email-templates/access-request-approved";
import { renderAccessRequestDeniedEmail } from "../lib/email-templates/access-request-denied";
import { renderAccessRequestInboundEmail } from "../lib/email-templates/access-request-inbound";
import { recordAuditAction } from "../lib/audit";

// ─────────────────────────────────────────────────────────────────────
// Types — the shape the route layer hands back to clients
// ─────────────────────────────────────────────────────────────────────

export type DriverAccessRequestStatus =
  | "pending"
  | "approved"
  | "denied"
  | "withdrawn";

export type DriverAccessRequestTrigger =
  | "self_request"
  | "email_domain_match";

export interface AccessRequestSummary {
  id: string;
  userId: string;
  userEmail: string;
  userDisplayName: string | null;
  installationId: string;
  installationDisplayName: string;
  siteDisplayName: string;
  triggeredBy: DriverAccessRequestTrigger;
  status: DriverAccessRequestStatus;
  denialReason: string | null;
  orgEmailDomain: { domain: string; policy: string } | null;
  createdAt: string;
  reviewedAt: string | null;
  reviewedBy: { id: string; email: string } | null;
  resultingMembershipId: string | null;
}

export interface ListTotals {
  pending: number;
  approved: number;
  denied: number;
  withdrawn: number;
}

// Frontend display URL builders — kept here so the email + the
// resource-linkable URL stay in sync. Both fall back to staging when
// no Origin header is in scope (cron / queue contexts).
function defaultBaseUrl(): string {
  return "https://hlada-staging.straumvakt.workers.dev";
}

function buildDriverStatusUrl(baseUrl: string): string {
  return `${baseUrl}/account/access-requests`;
}

function buildDriverChargersUrl(baseUrl: string): string {
  return `${baseUrl}/chargers`;
}

function buildDriverSupportUrl(baseUrl: string): string {
  return `${baseUrl}/installations`;
}

function buildOperatorInboxUrl(baseUrl: string): string {
  return `${baseUrl}/people/access-requests`;
}

// ─────────────────────────────────────────────────────────────────────
// 1. createSelfRequest — driver-side write
// ─────────────────────────────────────────────────────────────────────

export interface CreateSelfRequestOutcome {
  ok: true;
  accessRequest: {
    id: string;
    installationId: string;
    status: DriverAccessRequestStatus;
    createdAt: string;
  };
}

export type CreateSelfRequestFailure =
  | { error: "installation_not_found" }
  | { error: "already_have_access" }
  | { error: "already_requested"; existingRequestId: string }
  | { error: "user_not_found" };

export async function createSelfRequest(
  db: PrismaClient,
  env: Env,
  userId: string,
  installationId: string,
  options: { baseUrl?: string } = {},
): Promise<CreateSelfRequestOutcome | CreateSelfRequestFailure> {
  // 1. Installation must exist. We also fetch the parent org + site for
  //    the email body and the operator routing target.
  const installation = await db.installation.findUnique({
    where: { id: installationId },
    select: {
      id: true,
      orgId: true,
      displayName: true,
      site: { select: { displayName: true } },
      organization: {
        select: {
          id: true,
          displayName: true,
          mainContactUserId: true,
          mainContact: {
            select: { id: true, email: true, displayName: true },
          },
        },
      },
    },
  });
  if (!installation) {
    return { error: "installation_not_found" };
  }

  // 2. Already has access? Walk membership → driver group → agreement
  //    → installation. We check for an active agreement covering this
  //    installation that the driver is a member of.
  const now = new Date();
  const existingMembership = await db.driverGroupMembership.findFirst({
    where: {
      userId,
      driverGroup: {
        agreement: {
          installationId: installation.id,
          status: "active",
          effectiveFrom: { lte: now },
          OR: [
            { effectiveUntil: null },
            { effectiveUntil: { gt: now } },
          ],
        },
      },
    },
    select: { id: true },
  });
  if (existingMembership) {
    return { error: "already_have_access" };
  }

  // 3. Already requested? Look for the same (user, installation, pending).
  const existingPending = await darDb(db).driverAccessRequest.findFirst({
    where: {
      userId,
      installationId: installation.id,
      status: "pending",
    },
    select: { id: true },
  });
  if (existingPending) {
    return { error: "already_requested", existingRequestId: existingPending.id };
  }

  // 4. Look up the driver — we need their email for the receipt email
  //    and the operator-inbound email.
  const user = await db.user.findUnique({
    where: { id: userId },
    select: { id: true, email: true, displayName: true },
  });
  if (!user) {
    // Token was valid but the user row vanished mid-request. Edge case;
    // surface as user_not_found so the route can 401.
    return { error: "user_not_found" };
  }

  // 5. Write the row + audit row in one transaction.
  const created = await db.$transaction(async (tx) => {
    const row = await (tx as any).driverAccessRequest.create({
      data: {
        userId: user.id,
        installationId: installation.id,
        triggeredBy: "self_request",
        orgEmailDomainId: null,
        status: "pending",
      },
      select: {
        id: true,
        installationId: true,
        status: true,
        createdAt: true,
      },
    });
    await recordAuditAction(tx as unknown as PrismaClient, {
      orgId: installation.orgId,
      actorUserId: user.id,
      actorKind: "user",
      action: "driver_access_request.created",
      targetType: "driver_access_request",
      targetId: row.id,
      metadata: {
        installationId: installation.id,
        triggeredBy: "self_request",
      },
    });
    return row;
  });

  // 6. Send emails (fail-open). Don't block the response on email errors.
  const baseUrl = options.baseUrl ?? defaultBaseUrl();
  const driverName = user.displayName ?? user.email;

  const driverContent = renderAccessRequestSubmittedEmail({
    installationDisplayName: installation.displayName,
    siteDisplayName: installation.site?.displayName,
    driverName,
    createdAt: created.createdAt,
    statusUrl: buildDriverStatusUrl(baseUrl),
  });
  await sendEmail(env, {
    to: user.email,
    subject: driverContent.subject,
    html: driverContent.html,
    text: driverContent.text,
    tags: [{ name: "category", value: "access_request_submitted" }],
  }).catch((err: unknown) => {
    console.warn(
      `[driver-access-requests] driver receipt send threw: ${err instanceof Error ? err.message : String(err)}`,
    );
  });

  // Operator-inbound: pilot fans out to Organization.mainContact only.
  // When the contact-roles table grows we replace this with a fanout
  // to every role with billing.write on the org.
  if (installation.organization.mainContact?.email) {
    const operatorContent = renderAccessRequestInboundEmail({
      driverName,
      driverEmail: user.email,
      installationDisplayName: installation.displayName,
      siteDisplayName: installation.site?.displayName,
      requestedAt: created.createdAt,
      triggeredBy: "self_request",
      inboxUrl: buildOperatorInboxUrl(baseUrl),
    });
    await sendEmail(env, {
      to: installation.organization.mainContact.email,
      subject: operatorContent.subject,
      html: operatorContent.html,
      text: operatorContent.text,
      tags: [{ name: "category", value: "access_request_inbound" }],
    }).catch((err: unknown) => {
      console.warn(
        `[driver-access-requests] operator inbound send threw: ${err instanceof Error ? err.message : String(err)}`,
      );
    });
  } else {
    console.warn(
      `[driver-access-requests] org ${installation.orgId} has no main contact — skipped inbound email`,
    );
  }

  return {
    ok: true,
    accessRequest: {
      id: created.id,
      installationId: created.installationId,
      status: created.status as DriverAccessRequestStatus,
      createdAt: created.createdAt.toISOString(),
    },
  };
}

// ─────────────────────────────────────────────────────────────────────
// 2. listForOperator — operator inbox read
// ─────────────────────────────────────────────────────────────────────

export interface ListForOperatorInput {
  orgId: string;
  status?: DriverAccessRequestStatus;
  limit?: number;
}

export async function listForOperator(
  db: PrismaClient,
  input: ListForOperatorInput,
): Promise<{ requests: AccessRequestSummary[]; totals: ListTotals }> {
  const limit = Math.min(Math.max(input.limit ?? 50, 1), 200);

  // Status filter: default 'pending'. The 'all' sentinel isn't needed
  // because the route fans out totals separately; status is always one
  // of the four enum values for the row list.
  const whereStatus = input.status ?? "pending";

  // Scope: installations whose orgId = the requested org. This is the
  // tenant-isolation boundary — a manager at org A must not see org B's
  // requests. WhereInput type isn't exposed yet by the local generated
  // client (see the escape-hatch comment above darDb), so we keep the
  // structural shape inline and hand it as `any` to findMany/groupBy.
  const where: Record<string, unknown> = {
    status: whereStatus,
    installation: { orgId: input.orgId },
  };

  const [rows, totalsAgg] = await Promise.all([
    darDb(db).driverAccessRequest.findMany({
      where,
      orderBy: [{ createdAt: "desc" }],
      take: limit,
      select: {
        id: true,
        userId: true,
        installationId: true,
        triggeredBy: true,
        status: true,
        denialReason: true,
        createdAt: true,
        reviewedAt: true,
        resultingMembershipId: true,
        user: {
          select: { id: true, email: true, displayName: true },
        },
        installation: {
          select: {
            id: true,
            displayName: true,
            site: { select: { displayName: true } },
          },
        },
        orgEmailDomain: {
          select: { domain: true, policy: true },
        },
        reviewedBy: {
          select: { id: true, email: true },
        },
      },
    }),
    darDb(db).driverAccessRequest.groupBy({
      by: ["status"],
      where: { installation: { orgId: input.orgId } },
      _count: { _all: true },
    }),
  ]);

  const totals: ListTotals = {
    pending: 0,
    approved: 0,
    denied: 0,
    withdrawn: 0,
  };
  for (const t of totalsAgg as Array<{
    status: DriverAccessRequestStatus;
    _count: { _all: number };
  }>) {
    if (t.status in totals) {
      totals[t.status] = t._count._all;
    }
  }

  const requests: AccessRequestSummary[] = rows.map((r: any) => ({
    id: r.id,
    userId: r.userId,
    userEmail: r.user.email,
    userDisplayName: r.user.displayName,
    installationId: r.installationId,
    installationDisplayName: r.installation.displayName,
    siteDisplayName: r.installation.site?.displayName ?? "",
    triggeredBy: r.triggeredBy as DriverAccessRequestTrigger,
    status: r.status as DriverAccessRequestStatus,
    denialReason: r.denialReason,
    orgEmailDomain: r.orgEmailDomain
      ? { domain: r.orgEmailDomain.domain, policy: r.orgEmailDomain.policy }
      : null,
    createdAt: r.createdAt.toISOString(),
    reviewedAt: r.reviewedAt ? r.reviewedAt.toISOString() : null,
    reviewedBy: r.reviewedBy
      ? { id: r.reviewedBy.id, email: r.reviewedBy.email }
      : null,
    resultingMembershipId: r.resultingMembershipId,
  }));

  return { requests, totals };
}

// ─────────────────────────────────────────────────────────────────────
// 3. approveRequest — operator approves
// ─────────────────────────────────────────────────────────────────────

export interface ApproveRequestOutcome {
  ok: true;
  membership: { id: string; driverGroupId: string };
  /** True when the request was already approved and we returned the existing membership. */
  alreadyExisted: boolean;
}

export type ApproveRequestFailure =
  | { error: "request_not_found" }
  | { error: "request_not_pending" }
  | { error: "no_driver_group_for_installation" }
  | { error: "installation_org_mismatch" };

export async function approveRequest(
  db: PrismaClient,
  env: Env,
  requestId: string,
  reviewerUserId: string,
  options: {
    /** Used by the route to assert the reviewer has authority on the right org. */
    expectedInstallationOrgId?: string;
    baseUrl?: string;
  } = {},
): Promise<ApproveRequestOutcome | ApproveRequestFailure> {
  // 1. Load the request + installation/org for routing.
  const request = await darDb(db).driverAccessRequest.findUnique({
    where: { id: requestId },
    select: {
      id: true,
      userId: true,
      installationId: true,
      status: true,
      resultingMembershipId: true,
      user: {
        select: { id: true, email: true, displayName: true },
      },
      installation: {
        select: {
          id: true,
          orgId: true,
          displayName: true,
          site: { select: { displayName: true } },
        },
      },
    },
  });
  if (!request) return { error: "request_not_found" };

  // Optional org-match guard — caller hands us the org they expect this
  // request to belong to (resolved from session/permission scope).
  if (
    options.expectedInstallationOrgId &&
    options.expectedInstallationOrgId !== request.installation.orgId
  ) {
    return { error: "installation_org_mismatch" };
  }

  // Idempotency: already approved + resultingMembershipId still exists.
  if (request.status === "approved" && request.resultingMembershipId) {
    const existing = await db.driverGroupMembership.findUnique({
      where: { id: request.resultingMembershipId },
      select: { id: true, driverGroupId: true },
    });
    if (existing) {
      return {
        ok: true,
        membership: { id: existing.id, driverGroupId: existing.driverGroupId },
        alreadyExisted: true,
      };
    }
    // resultingMembershipId points at a deleted row — fall through and
    // re-create. The 'approved' row stays approved; only the membership
    // pointer gets refreshed.
  }

  // Disallow approving a row that's denied/withdrawn — operator must
  // open a fresh row if the situation has changed.
  if (
    request.status !== "pending" &&
    request.status !== "approved"
  ) {
    return { error: "request_not_pending" };
  }

  // 2. Pick the DriverGroup. Strategy:
  //    - Walk: Installation → Agreements where this installation is the
  //      target AND status='active' AND effective window includes now.
  //    - Of all DriverGroups under those agreements, pick the one with
  //      the smallest member count (spread load). Ties broken by group
  //      createdAt asc — deterministic and re-runnable.
  //    - If there are zero groups → error: no_driver_group_for_installation.
  const now = new Date();
  const groups = await db.driverGroup.findMany({
    where: {
      agreement: {
        installationId: request.installation.id,
        status: "active",
        effectiveFrom: { lte: now },
        OR: [{ effectiveUntil: null }, { effectiveUntil: { gt: now } }],
      },
    },
    select: {
      id: true,
      createdAt: true,
      _count: { select: { memberships: true } },
    },
  });
  if (groups.length === 0) {
    return { error: "no_driver_group_for_installation" };
  }
  groups.sort((a: any, b: any) => {
    const diff = a._count.memberships - b._count.memberships;
    if (diff !== 0) return diff;
    return a.createdAt.getTime() - b.createdAt.getTime();
  });
  const chosenGroup = groups[0];

  // 3. Idempotency at the membership level: if the driver is already a
  //    member of the chosen group, link the existing row and mark the
  //    request approved without duplicating.
  const existingMembership = await db.driverGroupMembership.findUnique({
    where: {
      driverGroupId_userId: {
        driverGroupId: chosenGroup.id,
        userId: request.userId,
      },
    },
    select: { id: true, driverGroupId: true },
  });

  // 4. Single transaction: create-or-link membership + flip request +
  //    audit row.
  const reviewedAt = new Date();
  const result = await db.$transaction(async (tx) => {
    const membership =
      existingMembership ??
      (await tx.driverGroupMembership.create({
        data: {
          driverGroupId: chosenGroup.id,
          userId: request.userId,
        },
        select: { id: true, driverGroupId: true },
      }));

    await (tx as any).driverAccessRequest.update({
      where: { id: request.id },
      data: {
        status: "approved",
        reviewedByUserId: reviewerUserId,
        reviewedAt,
        resultingMembershipId: membership.id,
        // Don't clear denialReason — it stays null in the pending→approved
        // case; if this is the re-create path after a deleted membership,
        // the previous denialReason (if any) was already null because the
        // row was 'approved' before.
      },
    });

    await recordAuditAction(tx as unknown as PrismaClient, {
      orgId: request.installation.orgId,
      actorUserId: reviewerUserId,
      actorKind: "user",
      action: "driver_access_request.approved",
      targetType: "driver_access_request",
      targetId: request.id,
      metadata: {
        userId: request.userId,
        installationId: request.installation.id,
        driverGroupId: chosenGroup.id,
        membershipId: membership.id,
        relinked: !!existingMembership,
      },
    });
    return membership;
  });

  // 5. Email (fail-open).
  const baseUrl = options.baseUrl ?? defaultBaseUrl();
  const reviewer = await db.user.findUnique({
    where: { id: reviewerUserId },
    select: { displayName: true, email: true },
  });
  const driverName = request.user.displayName ?? request.user.email;
  const content = renderAccessRequestApprovedEmail({
    installationDisplayName: request.installation.displayName,
    siteDisplayName: request.installation.site?.displayName,
    driverName,
    approvedAt: reviewedAt,
    chargersUrl: buildDriverChargersUrl(baseUrl),
    approvedBy: reviewer?.displayName ?? reviewer?.email,
  });
  await sendEmail(env, {
    to: request.user.email,
    subject: content.subject,
    html: content.html,
    text: content.text,
    tags: [{ name: "category", value: "access_request_approved" }],
  }).catch((err: unknown) => {
    console.warn(
      `[driver-access-requests] approval email threw: ${err instanceof Error ? err.message : String(err)}`,
    );
  });

  return {
    ok: true,
    membership: { id: result.id, driverGroupId: result.driverGroupId },
    alreadyExisted: !!existingMembership,
  };
}

// ─────────────────────────────────────────────────────────────────────
// 4. denyRequest — operator denies with a required reason
// ─────────────────────────────────────────────────────────────────────

export interface DenyRequestOutcome {
  ok: true;
}

export type DenyRequestFailure =
  | { error: "request_not_found" }
  | { error: "request_not_pending" }
  | { error: "denial_reason_required" }
  | { error: "installation_org_mismatch" };

export async function denyRequest(
  db: PrismaClient,
  env: Env,
  requestId: string,
  reviewerUserId: string,
  denialReason: string,
  options: {
    expectedInstallationOrgId?: string;
    baseUrl?: string;
  } = {},
): Promise<DenyRequestOutcome | DenyRequestFailure> {
  const reason = denialReason.trim();
  if (reason.length === 0) {
    return { error: "denial_reason_required" };
  }

  const request = await darDb(db).driverAccessRequest.findUnique({
    where: { id: requestId },
    select: {
      id: true,
      userId: true,
      installationId: true,
      status: true,
      user: {
        select: { id: true, email: true, displayName: true },
      },
      installation: {
        select: {
          id: true,
          orgId: true,
          displayName: true,
          site: { select: { displayName: true } },
        },
      },
    },
  });
  if (!request) return { error: "request_not_found" };

  if (
    options.expectedInstallationOrgId &&
    options.expectedInstallationOrgId !== request.installation.orgId
  ) {
    return { error: "installation_org_mismatch" };
  }

  if (request.status !== "pending") {
    return { error: "request_not_pending" };
  }

  const reviewedAt = new Date();
  await db.$transaction(async (tx) => {
    await (tx as any).driverAccessRequest.update({
      where: { id: request.id },
      data: {
        status: "denied",
        denialReason: reason,
        reviewedByUserId: reviewerUserId,
        reviewedAt,
      },
    });
    await recordAuditAction(tx as unknown as PrismaClient, {
      orgId: request.installation.orgId,
      actorUserId: reviewerUserId,
      actorKind: "user",
      action: "driver_access_request.denied",
      targetType: "driver_access_request",
      targetId: request.id,
      metadata: {
        userId: request.userId,
        installationId: request.installation.id,
        denialReason: reason,
      },
    });
  });

  // Send the denial email (fail-open).
  const baseUrl = options.baseUrl ?? defaultBaseUrl();
  const driverName = request.user.displayName ?? request.user.email;
  const content = renderAccessRequestDeniedEmail({
    installationDisplayName: request.installation.displayName,
    siteDisplayName: request.installation.site?.displayName,
    driverName,
    denialReason: reason,
    deniedAt: reviewedAt,
    supportUrl: buildDriverSupportUrl(baseUrl),
  });
  await sendEmail(env, {
    to: request.user.email,
    subject: content.subject,
    html: content.html,
    text: content.text,
    tags: [{ name: "category", value: "access_request_denied" }],
  }).catch((err: unknown) => {
    console.warn(
      `[driver-access-requests] denial email threw: ${err instanceof Error ? err.message : String(err)}`,
    );
  });

  return { ok: true };
}
